version: '3.9'

networks:
  net:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/chroma
      - index_data:/index_data
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    networks:
      - net

volumes:
  index_data:
    driver: local
